// <auto-generated />
namespace ESGIForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class tata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tata));
        
        string IMigrationMetadata.Id
        {
            get { return "201406221237093_tata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
